### PR TITLE
Style updates for demo

### PR DESCRIPTION
**Pull request by adelevie**
WIP, @andrewmaier, please identify remaining TODOs and indicate when this is ready for merge.

### CODE REVIEW

**Comment by andrewmaier** [comment]
Last todo is migrating away from Google Web Fonts! This is perfectly demo-able in its current form, though :)

**Comment by adelevie** [comment]
Sweet. What are the font names you need? Do you know of a location where they can be downloaded?

Also, it looks like you need to rebase. I'm happy to do this if you want.

**Comment by adelevie** [comment]
rebased

**Comment by adelevie** [comment]
rebased

**Comment by adelevie** [comment]
:ship: thanks @andrewmaier!

**Pull request merged**
